### ISSUE TITLE
Build breaking with yarn v0.24.6 on OSX (running web + native)

### ISSUE THREAD

**Issue by mairh** [sysgears/apollo-universal-starter-kit#217] opened 2017-06-04 21:57 UTC
This is just a heads up that the build is breaking when running `yarn watch` using `v0.24.6`

Failing with error 

```
yarn watch v0.24.6
$ node tools/webpack.entry watch
Using Webpack DLL vendor bundle
[HPM] Proxy created: !/*.hot-update.{json,js}  ->  http://localhost:8080
webpack-for-web-frontend Webpack web-frontend dev server listening on 3000
webpack-for-ios-frontend Webpack ios-frontend dev server listening on 3020
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nish/Documents/code/easymedi/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nish/Documents/code/easymedi/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nish/Documents/code/easymedi/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nish/Documents/code/easymedi/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10) code: 'MODULE_NOT_FOUND' }
```

It seems like this is a common issue

https://github.com/trentm/node-bunyan/issues/216
https://github.com/react-community/create-react-native-app/issues/135

Workaround is to use `npm install` and `npm run watch` instead of `yarn` and `yarn watch`

**Comment by OmgImAlexis** [comment] 2017-06-07 04:03
If yarn adds a way to change the Python version being used this will be fixed as building with Python 2.7 instead of Python 3 fixes this issue.

Ref: https://github.com/yarnpkg/yarn/issues/3519

**Comment by mairh** [comment] 2017-06-09 13:48
Seem like `yarn v0.24.6`started working for me now. Not sure what has changed. If someone else can confirm that `yarn watch` is running without any problem then we can close this issue.

**Comment by vlasenko** [comment] 2017-06-09 20:09
Yes, working for me now too. And I have faced this bug previously. Not sure what has changed, but it works now. Closing this issue.

**Comment by mairh** [comment] 2017-06-12 14:42
Reopening since I am facing the same issue again using the same version.
<img width="815" alt="screen shot 2017-06-12 at 17 41 50" src="https://user-images.githubusercontent.com/4072250/27039374-711656da-4f96-11e7-9e52-1e438b7ca9bf.png">

**Comment by vlasenko** [comment] 2017-06-12 14:51
@mairh Doesn't reproduces for me now

**Comment by mairh** [comment] 2017-06-12 15:58
@vlasenko Are you using the same `yarn` version?

Could you try the following options (if you haven't done already)

1) Remove `build` folder
2) Remove `node_modules`
3) Remove `.expo`
2) Try `android: true` and then with `ios: true`

**Comment by vlasenko** [comment] 2017-06-12 16:01
Yes, I'm using the yarn `0.24.6` which is the latest stable at the moment and I'm doing fresh clone with `android: true`

**Comment by mairh** [comment] 2017-06-12 16:02
Although, it shouldn't make any difference, but could be it only be happening on `ios: true` ?

**Comment by mairh** [comment] 2017-06-12 16:02
@mitjade When you have time could you give it a try?

**Comment by mitjade** [comment] 2017-06-12 16:31
@mairh Will do in a few hours.

**Comment by mitjade** [comment] 2017-06-12 20:51
Currently it's working for me. I had some problems with yarn when I was running also iOS simulator. For web only no problems so far.

**Comment by mairh** [comment] 2017-06-12 21:06
yes, for the web only it works fine. I'll keep this issue open for a short while and see if the yarn problem is just hit and trail or something else. Thanks for checking it out though.

**Comment by OmgImAlexis** [comment] 2017-06-13 01:24
@mairh this issue is because of bunyan it won't just randomly go away you'll need to either switch to using npm install for now with python 2.7 set or wait for yarn to add a python flag as I stated above.

Bunyan issue: https://github.com/trentm/node-bunyan/issues/216
Yarn issue: https://github.com/yarnpkg/yarn/issues/3519

**Closed** 2017-07-11 13:32 UTC

**Comment by vlasenko** [comment] 2017-07-11 13:39
This should be fixed now via:
https://github.com/sysgears/apollo-universal-starter-kit/commit/2af3d4a28ffd57f836ad5fcc421fc6d15c1ebb3c

It utilizes latest `xdl`, which has commit:
https://github.com/expo/xdl/commit/00125da4f0aa5eb0959dc4c978f957af32747376

`@expo/bunyan` doesn't depend on `dtrace-provider` that causes this problem.
