### ISSUE TITLE
Webpack development server not working

### ISSUE THREAD

**Issue by coooolers** [sysgears/apollo-universal-starter-kit#833] opened 2018-08-30 06:39 UTC
When I make changes in the code, Webpack development server is not compiling the code on-the-fly. Also, both the browser and the Android mobile emulator are not getting refreshed automatically.

I am using the latest copy of the code.

Am I wrong somewhere, or is it because of upgrade to Webpack 4, or some other reason?

When I run yarn watch, I get this error:
android-webpack error protocol fault (couldn't read status): Connection reset by peer

Even I restarted the machine and the Android Studio / AVD, but the error is still there. I could not even login from the web browser. 

Any hints?

Thanks

**Comment by vlasenko** [comment] 2018-08-30 07:27
@coooolers Please provide exact reproduction steps and full terminal output

**Comment by vlasenko** [comment] 2018-08-30 07:37
@coooolers P.S. `error protocol fault (couldn't read status)` is an adb error - it has nothing to do with the kit:
https://stackoverflow.com/questions/33633536/android-adb-error-error-protocol-fault-couldnt-read-status-invalid-argumen

**Comment by coooolers** [comment] 2018-08-30 07:46
I wiped the AVD existing data using the  "Wipe Data" command. Restarted the AVD, ran yarn watch and the "android-webpack error protocol fault" error is resolved.

Then I set the config.builders.android.enabled to false (disabling the mobile development) and ran yarn watch. Tried to login from a web browser but nothing happens.

Console Output is as follows:
Entrypoint index [big] = index.5cc28da8178d9f5b6fd1.js index.5cc28da8178d9f5b6fd1.js.map
backend debug read session { csrfToken: 'eeda17a302ca517a6448bd179fd42786' }
backend debug {"data":{"currentUser":null}} <= currentUser
backend debug {"data":{"serverCounter":{"amount":5,"__typename":"Counter"}}} <= serverCounterQuery
backend debug read session undefined
backend debug write session { csrfToken: '72189b3ed767e93ef59acfedc2966f5e' }
backend debug {"data":{"currentUser":null}} <= currentUser
backend debug read session undefined
backend debug write session { csrfToken: '2422c505acea3081afe48e22d4f00637' }
backend debug {"data":{"currentUser":null}} <= currentUser
backend debug read session undefined
backend debug write session { csrfToken: '2f402e739b92bcf8d7d8ccd40441ecd8' }
backend debug {"data":{"currentUser":null}} <= currentUser
backend debug read session { csrfToken: 'eeda17a302ca517a6448bd179fd42786' }

**Comment by vlasenko** [comment] 2018-08-30 07:53
@coooolers From this output - it looks like HTTP server-side cookies get regenerated all the time. I have cloned latest `master` and I don't see any problems with sign in. As a work around you can disable server-side sessions in `config/user.js` -> `access -> session` - set it to `false` to check that they are broken for you.

**Comment by coooolers** [comment] 2018-08-30 08:14
No more cookies regeneration. As you said, this is a workaround, any permanent solution?

But the Login / Register still not working. I am able to create a new post though.

Let me download the latest master branch and merge my changes to it.

**Comment by vlasenko** [comment] 2018-08-30 08:17
@coooolers Please provide exact reproduction steps. The code from `master` works for me - no issues with Sign In or Register. If you made some modifications to the code - maybe its your modifications that trigger the issues, as I don't have access to your modifications there is no way for me to find out whats wrong.

**Comment by vlasenko** [comment] 2018-08-30 09:33
@coooolers Thanks for the trust, but it is out of scope for the open source projects like this, to look at private code and figure out whats wrong with it.

**Closed by vlasenko** 2018-08-30 09:33 UTC
