### ISSUE TITLE
API Specs with authentication

### ISSUE THREAD

**Issue by theWeird** [sysgears/apollo-universal-starter-kit#669] opened 2018-03-06 14:39 UTC
For some server-specs it would be useful to have authentication before running the tests.

e.g. to ensure a users profile can only be edited if the authenticated user is the same or at least an admin.

Maybe you could add an example to serverside userspecs how to authenticate in before-part of a test suite to run tests with permissions of a specific user.

I tried by adding these to a spec
```javascript
      const { data: { login } } = await apollo.mutate({
        mutation: LOGIN,
        variables: { input: { username: 'admin', password: 'admin' } },
      });

      await apollo.writeQuery({ query: CURRENT_USER_QUERY, data: { currentUser: login.user } });
```
But still resolvers called by spec queries dont have a `context.user` object to check for authentication and authorization.

**Comment by vlasenko** [comment] 2018-03-06 14:50
@theWeird Yes, we think it is a good idea to have examples - how to write the specs for checking that the authorization logic implemented properly in the API

**Comment by theWeird** [comment] 2018-03-07 09:48
I'm currently building my app based on your abandoned PR #522.
Hope I am able to adopt it then ;)

**Comment by vlasenko** [comment] 2018-03-07 09:50
@theWeird We have a newer implementation of this PR, which is about to be integrated, I hope we will merge it this week:
https://github.com/sysgears/apollo-universal-starter-kit/pull/644

**Comment by theWeird** [comment] 2018-03-07 12:16
I've seen it. But I already migrated auth from #522 into my app.

Anyway.
I assume to be able to use an authenticated session after login it is required to grab informations from response headers in BatchHttpLink afterware.
Just found out, that the used versions of BatchHttpLink dont pass these in the context information to the afterware, so a newer version of apollo-link-http-batch is required. Unfortunatly the required version breaks with apollo-fetch, so it seems to be more to do than just to write a test ...

**Comment by vlasenko** [comment] 2018-03-07 12:29
@theWeird It is not a job of BatchHttpLink to work on network-level. It is a job of ApolloFetch to work at network-level, with ApolloFetch you have control on passed headers

**Comment by theWeird** [comment] 2018-03-07 13:42
Well, now I came up with some code to grab cookies from responses and add headers to requests.
But I wonder how the cookie session-string has to be added to the fetch options, so the server can recognize the session and provide a context.user object to the resolvers.

After logging in like shown in the start post, my code (see below) creates a options object like this on the next request.
But none of the used keys seems to be recognized by the server.
```javascript
{ headers: 
   { cookie: 'session=LeCt9O9cjWjgLs47oU84dA%3D%3D.1eo7CeIk3dqEmZMjD%2BPF8FBXRjqbWhOSRCuxfyXj3XnqURBmxaLgJCMKfrPf2HsaMPi%2BytuWWEsmKXKS2dNujA%3D%3D.tx2IEjdTQlcmaHQsSeax3Zl8Xlt5rAgS0Ty9Ya%2B%2BfJM%3D',
     Cookie: 'session=LeCt9O9cjWjgLs47oU84dA%3D%3D.1eo7CeIk3dqEmZMjD%2BPF8FBXRjqbWhOSRCuxfyXj3XnqURBmxaLgJCMKfrPf2HsaMPi%2BytuWWEsmKXKS2dNujA%3D%3D.tx2IEjdTQlcmaHQsSeax3Zl8Xlt5rAgS0Ty9Ya%2B%2BfJM%3D',
     authorization: 'session=LeCt9O9cjWjgLs47oU84dA%3D%3D.1eo7CeIk3dqEmZMjD%2BPF8FBXRjqbWhOSRCuxfyXj3XnqURBmxaLgJCMKfrPf2HsaMPi%2BytuWWEsmKXKS2dNujA%3D%3D.tx2IEjdTQlcmaHQsSeax3Zl8Xlt5rAgS0Ty9Ya%2B%2BfJM%3D' } }
```
Do you have clue on a notation that could work?

```javascript
let sessionCookie = false;

  const middleware = ({ options }, next) => {
    console.error("opts", options);
    if(sessionCookie) {
      const cookie = sessionCookie.split(';')[0];
      if (!options.headers) {
        options.headers = {};  // Create the headers object if needed.
      }
      options.headers['cookie'] = cookie;
      options.headers['Cookie'] = cookie;
      options.headers['authorization'] = cookie;
    }
    next();
  };
  const middleware2 = ({ options }, next) => {
    console.error("opt result ", options);
    next();
  };

  const afterware = ({ response, options }, next) => {
    if(response.headers.get('set-cookie')) {
      console.info('new session id');
      sessionCookie = response.headers.get('set-cookie');
    }
    next();
  };
  fetch.batchUse(middleware);
  fetch.batchUse(middleware2);
  fetch.use(middleware);
  fetch.use(middleware2);
  fetch.batchUseAfter(afterware);
```

**Comment by theWeird** [comment] 2018-03-07 15:53
The problem seems to be that fetch doesn't grab set-cookies headers or doesn't apply them to follow-up requests and I can't set a cookie by myself.

Do you have an idea on how to fix one of these?

**Comment by vlasenko** [comment] 2018-03-07 16:05
@theWeird You set client-side cookies via web browser, not via fetch.
Check also `fetch` `credentials` option:
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

**Comment by theWeird** [comment] 2018-03-07 17:04
In meantime I tried to pass credentials 'include' to fetch as well as to HttpLink
```javascript
  fetch.batchUse(({ options }, next) => {
    options.credentials = 'include';
    next();
  });
  fetch.use(({ options }, next) => {
    options.credentials = 'include';
    next();
  });
....
new BatchHttpLink({ fetch, credentials: 'include' })
```
I also modified the server code to check, if a session cookie was sent:
```javascript
console.error("REQUEST READ SESSION ", req.universalCookies.get('session', { doNotParse: true }));
```
But still apollo-fetch doesn't apply the session cookies to further requests.
Maybe because running tests with apollo-fetch has no browser involved?

**Comment by vlasenko** [comment] 2018-03-07 17:35
@theWeird Okay, when you run tests, if you pass correctly formatted `cookie` value into headers for the `fetch`, you will get cookie back in the server. You should have the code to set `cookie` after this line:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/src/testHelpers/integrationSetup.js#L30

The only catch is to properly set the cookie. I can confirm that when I set cookie from there, I get the cookie here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/packages/server/src/modules/user/auth/token.js#L7

The same is for session. You should set correct cookie value though, so that auth code accepted it, because only having some cookie value is not enough, it should be a valid value from the point of view of auth code

**Comment by vlasenko** [comment] 2018-03-07 17:38
@theWeird This is my code that I have used to test that setting cookies in the headers for `fetch` works as expected in the tests:
```
  fetch.batchUse(({ options }, next) => {
    options.credentials = 'include';
    options.headers = {
      cookie:
        '_ga=GA1.1.711913065.1496210283; _gid=GA1.1.1473923677.1520420173; x-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZnVsbE5hbWUiOm51bGx9LCJpYXQiOjE1MjA0MjY3MDIsImV4cCI6MTUyMDQyNjc2Mn0.7fN10pyj4T_UWus5EfkpEV9wpwuGx8OfuExpflJ9924; x-refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE1MjA0MjY3MDIsImV4cCI6MTUyMTAzMTUwMn0.ibVjFClfKrXwfP8Q3GCkZhJKVHuIwfiyqFmhOVhj8N8; r-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiZnVsbE5hbWUiOm51bGx9LCJpYXQiOjE1MjA0MjY3MDIsImV4cCI6MTUyMDQyNjc2Mn0.7fN10pyj4T_UWus5EfkpEV9wpwuGx8OfuExpflJ9924; r-refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJpYXQiOjE1MjA0MjY3MDIsImV4cCI6MTUyMTAzMTUwMn0.ibVjFClfKrXwfP8Q3GCkZhJKVHuIwfiyqFmhOVhj8N8'
    };

    next();
  });
```

**Comment by vlasenko** [comment] 2018-03-07 17:42
@theWeird Actually it might not work the same for sessions, because for sessions I was using `httpOnly`, i.e. server-side cookies as far as I remember in the code that you have integration. It is very difficult to help you though, since you have integrated some code that we are not maintaining and you have some custom code and I don't see any of these. So I'm pretty much blind

**Comment by theWeird** [comment] 2018-03-08 08:33
httpOnly was the best hint.
I modified set of the cookie as follows:
```javascript
req.universalCookies.set('session', encryptSession(session), {
    httpOnly: !__TEST__,  // disable in test mode, enable anywhere else
    secure: !__DEV__,
    maxAge: 7 * 24 * 3600,
  });
```

Now fetch makes use of the cookies without any middle- or afterware and server can read the session cookie without `credentials=include` explicit set.

Thank you very much.

**Comment by vlasenko** [comment] 2018-03-08 08:38
@theWeird I'm glad you have managed to find the way ahead. But the next step IMO is to actually use GraphQL mutations to login and then somehow reuse the cookies set by server code so that you don't have to set cookies in the tests yourself.
E.g. make your code 
``` js
      const { data: { login } } = await apollo.mutate({
        mutation: LOGIN,
        variables: { input: { username: 'admin', password: 'admin' } },
      });

      await apollo.writeQuery({ query: CURRENT_USER_QUERY, data: { currentUser: login.user } });
```
to actually work as expected in the test, by intercepting server response in the `fetch` afterware and memorize cookies in memory and then pass these cookies back to server in request headers in `fetch` middleware.

**Comment by vlasenko** [comment] 2018-03-28 15:13
Closing, because topic starter has found the solution

**Closed by vlasenko** 2018-03-28 15:13 UTC
