### ISSUE TITLE
First comments appears twice

### ISSUE THREAD

**Issue by matseriksen** [sysgears/apollo-universal-starter-kit#428] opened 2017-10-12 14:12 UTC
When I add a comment to a post it appears twice in the comment list, you have to refresh the page for the comment to only show up once as it should be. It only happens to the first comment you add.

**Comment by mitjade** [comment] 2017-10-12 14:14
@matseriksen Thanks for reporting. Noticed this my self, but have not yet taken a look what is the problem. Will do shortly.

**Comment by mitjade** [comment] 2017-10-13 11:37
Looks like a problem with `optimisticResponse` and `apollo` v2. This bug was not present in v1 and only happens after v2 was merged to master.

**Comment by mitjade** [comment] 2017-10-13 11:39
The record that is added through `optimisticResponse` does not get removed when the response from the server arrives.

**Comment by vlasenko** [comment] 2017-10-13 12:08
@mitjade Maybe we should comment out optimistic response for now with the mark that we observe bug in Apollo v2?

**Comment by mitjade** [comment] 2017-10-13 12:10
@vlasenko I am investigating this out now.

**Comment by mitjade** [comment] 2017-10-13 12:37
@vlasenko There seems to be no issue for this in `apollo-client`. They recommend using `update` instead of `updateQueries`, witch I tried and also does not work for me. I keep getting some `Can't find field XXX on object (ROOT_QUERY) {`. `GitHunt-React` example is still using v1 and `updateQueries`. I do not know how to solve this, but comment it out and wait for a fix.

**Comment by mitjade** [comment] 2017-10-13 12:42
Commented out `optimisticResponse` for now, until this gets fixed in `apollo` v2.

**Comment by mitjade** [comment] 2017-10-17 08:11
Also adding new post does not add it to the cache. Having a separate browser open, it seems to be added correctly through subscriptions.

**Comment by vlasenko** [comment] 2017-10-17 08:31
@mitjade Mitja, this sounds like problem in `apollo-cache-inmemory`. We are using `0.2.0-beta.2`, but there are like dozen releases after that of this library. Maybe we can try our luck with the latest release?

**Comment by mitjade** [comment] 2017-10-17 08:32
@vlasenko Will update on my side and check if this will fix something. Anyway I think we can upgrade the packages.

**Comment by vlasenko** [comment] 2017-10-17 08:34
@mitjade Yep, we can upgrade them to the latest versions anyway.

**Comment by mitjade** [comment] 2017-10-17 08:53
@vlasenko Am doing this now, just so we do not both do it :)

**Comment by vlasenko** [comment] 2017-10-17 09:00
@mitjade Not going to happen :) I'm fully focused on `spin.js`

**Comment by mitjade** [comment] 2017-10-17 09:07
@vlasenko Updated to latest `apollo` packages. Does not solve any of the problems :(

**Comment by vlasenko** [comment] 2017-10-17 09:10
@mitjade At least we know, thank you Mitja!

**Comment by mitjade** [comment] 2017-10-22 08:44
https://github.com/apollographql/apollo-client/issues/2368

**Comment by mitjade** [comment] 2017-10-25 11:24
Adding and editing posts has been resolved in latest packages. Double insert is still and issue.

**Comment by sakhmedbayev** [comment] 2017-10-25 11:33
In `PostComment` commenting out `updateQuery` solved the problem for me

```
const PostCommentsWithApollo = compose(
  graphql(ADD_COMMENT, {
    props: ({ mutate }) => ({
      addComment: (content, postId) =>
        mutate({
          variables: { input: { content, postId } },
          optimisticResponse: {
            addComment: {
              id: -1,
              content: content,
              __typename: 'Comment'
            }
          },
          // updateQueries: {
          //   post: (prev, { mutationResult: { data: { addComment } } }) => {
          //     if (prev.post) {
          //       return AddComment(prev, addComment);
          //     }
          //   }
          // }
        })
    })
  }),
```

**Comment by mitjade** [comment] 2017-10-25 11:36
@sakhmedbayev Yes. `updateQueries` seems to be the problem. But now you are only relying on sockets to update the data. Am investigating this now, if rewriting `updateQueries ` to `update` would solve the problem, since `updateQueries ` will be deprecated.

**Comment by sakhmedbayev** [comment] 2017-10-25 11:53
I am not sure if it is relevant, but try to check [this tutorial ](https://dev-blog.apollodata.com/tutorial-graphql-subscriptions-client-side-40e185e4be76), specifically this part:

```
if (!data.channel.messages.find((msg) => msg.id === addMessage.id)){
  // Add our Message from the mutation to the end.
  data.channel.messages.push(addMessage);
}
```

**Comment by mitjade** [comment] 2017-10-25 12:25
I can reproduce the same scenario on [apollographql/GitHunt-React](https://github.com/apollographql/GitHunt-React).

**Comment by mairh** [comment] 2017-11-16 09:46
@mitjade Do we have any new news about this bug?

**Comment by mairh** [comment] 2017-11-16 09:47
ah ok. Saw this now https://github.com/apollographql/apollo-client/issues/2368

**Comment by mairh** [comment] 2017-11-16 09:49
I think this is a priority bug and very annoying to see result twice.

**Comment by mitjade** [comment] 2017-11-16 09:52
@mairh It is an `apollo-client` bug and since they seem to ignore it, the only thing I could do is find a workaround, but will rather wait for the fix.

**Comment by mairh** [comment] 2017-11-16 09:55
Yes, I am aware that it's not our fault. I was talking in a respect that they should have taken the task already.

**Comment by mitjade** [comment] 2017-11-16 09:57
@mairh I presume they are busy with other stuff, but there is some activity on this front. They first removed the `data` from the subscription result and now brought it back, so I guess it will be handled eventually.

**Comment by joe1chen** [comment] 2018-04-03 00:34
BTW, I just tested this behavior on master branch today and I don't see the double comment bug anymore.

**Comment by vlasenko** [comment] 2018-04-03 08:20
@joe1chen Great, thank you for reporting!

**Closed by vlasenko** 2018-04-03 08:20 UTC
Labels: bug
