### ISSUE TITLE
getting errors  async (ctx, next) 

### ISSUE THREAD

**Issue by veerjainATgmail** [sysgears/apollo-universal-starter-kit#709] opened 2018-04-25 12:13 UTC
node v10.0.0

**Comment by vlasenko** [comment] 2018-04-25 12:13
@veerjainATgmail How to reproduce?

**Comment by veerjainATgmail** [comment] 2018-04-25 12:17
apologies...i pressed comment button too early :)
i am assuming it wont support node v10. shall fallback to older version (in Ubuntu)

**Comment by veerjainATgmail** [comment] 2018-04-25 12:24
apollo-universal-starter-kit-stable/node_modules/apollo-upload-server/lib/main/index.js:51
  return async (ctx, next) => {
               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.apollo-upload-server 

I am using Ubuntu, node v6.11.5 with the latest/stable apollo-universal-starter-kit
Anyone else seen the same issue?

**Comment by vlasenko** [comment] 2018-04-25 13:13
@veerjainATgmail I assume this is a bug in `apollo-upload-server` it should distribute js files with `async` in them

**Comment by vlasenko** [comment] 2018-04-25 13:13
@veerjainATgmail Have you tried to upgrade `apollo-upload-server`?

**Comment by veerjainATgmail** [comment] 2018-04-25 13:56
Hi, This is a new install. Fresh sandbox.

Mahaveer.

**Comment by vlasenko** [comment] 2018-04-25 14:44
@veerjainATgmail Have you tried to upgrade/downgrade `apollo-upload-server` package. It is clear that this is a packaging bug in it.

**Comment by veerjainATgmail** [comment] 2018-04-25 14:50
Thanks.!!!

Sure. Ill try that.

**Comment by vlasenko** [comment] 2018-04-25 14:52
`apollo-upload-server` requires Node >= 7.6. `yarn` requires "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0". So if you use `upload` feature of the kit, you must use Node >= 8.x. All this information is available from `yarn`

**Comment by vlasenko** [comment] 2018-04-25 14:55
I'm closing this, because it is not a bug in the kit. It is requirement of `apollo-upload-server` and `yarn` warns you about that.

**Closed by vlasenko** 2018-04-25 14:55 UTC
Labels: invalid

**Comment by vlasenko** [comment] 2018-04-25 15:00
@veerjainATgmail Btw, when you upgrade `apollo-upload-server` to the latest version `^5.0.0` - it no longer requires Node 7.6. I'm working to upgrading all the packages of the kit in master, so stay tuned, looks like we will be able to make `upload` work with Node starting from 6.11.1
