### ISSUE TITLE
Mobile app keep crashing after push to Expo

### ISSUE THREAD

**Issue by rancho90** [sysgears/apollo-universal-starter-kit#1131] opened 2019-07-28 04:39 UTC
**Describe the bug**
Using the latest stable branch, Mobile app works on localhost, but after publish to expo, it won't even open, just keep crashing. (Error: Application main has not been registered, and so on) 
Error log screenshot attached

**To Reproduce**
1. Get the latest stable branch code. (Commit: 2eaa0f9d37071c138b9b97add3ea27c5fc2e7857)

2. I followed the guide:
https://github.com/sysgears/apollo-universal-starter-kit/blob/master/docs/Deployment.md
To deploy to heroku

3. Heroku site works well,  then i updated root folder package.josn 
from
    "watch:android": "lerna run --scope={server,mobile} --parallel watch:android --stream",
to
    "watch:android": "lerna run --scope=mobile  watch:android --stream",

then I updated mobile config file with remote urls then
run yarn watch:android

4. It works well on localhost and connects to heroku server.

5. I then try to publish it to expo by doing:
cd packages/mobile
yarn expo publish

6. The project gets published to expo successfully. 

7. When I try to open it on my phone, it keeps crashing from every beginning. 

**Expected behavior**
The app should work the same as on localhost (yarn watch:android)

**Desktop (please complete the following information):**
 - OS: Mac Mojave v10.14

**Smartphone (please complete the following information):**
 - OS: Android 9

**Sreenshot**

![error-message](https://user-images.githubusercontent.com/11765805/62002176-b000fc80-b0b3-11e9-872a-4601479796fe.jpeg)

**Comment by vlasenko** [comment] 2019-08-14 13:59
@rancho90 In error message it tells that your version of Expo Client is outdated. You should remove it from mobile phone or emulator and relaunch the kit.

**Comment by rancho90** [comment] 2019-08-14 15:52
@vlasenko  It worked !!
Thanks so much for the help.

**Comment by rancho90** [comment] 2019-08-15 05:01
@vlasenko  I have clean installed with latest expo client and tested several times. But the issue is still there.
But the good news is that I have been able to locate the issue.
The issue appears to be redux is not properly minified by webpack or metro

You can easily reproduce this issue by updating one line of code:
 in /packages/mobile/package.json (Adding --minify flag)

"watch:android": "expo start --android **--minify**",

Then run yarn watch:android, you can easily reproduce this issue.

I am also attaching the error page.

Error: You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux.

![error2](https://user-images.githubusercontent.com/11765805/63073469-ca254200-bedd-11e9-96f0-4de6a91e7532.jpeg)

**Comment by vlasenko** [comment] 2019-08-15 05:49
@rancho90 I'm not sure where is the bug here, it tells you exactly what happens, you try to use Redux during development, but you minify it, this is not supported by Redux.

**Comment by rancho90** [comment] 2019-08-15 14:30
@vlasenko  The issue is that even in production mode, the same error happens.

When I try to publish to expo or build a standalone app. The same error shows up and keeps the app crashing. Because in the standalone app or on expo, minify is part of the production build process, then it starts crashing even in production mode.

There are 3 ways to reproduce this, you can pick any one:

1. If you want to mimic production mode locally, the same issue will occur. 
Try this to minic production mode locally: use flag --no-dev --minify,  it will reveal the error for you:
"watch:android": "expo start --android **--no-dev --minify**",

2. if you want to use remote expo. then publish it to expo, the issue will occur

3. if you want to use standalone production app, the issue will occur.

**Comment by vlasenko** [comment] 2019-08-15 14:37
@rancho90 This looks like more as Expo problem, but I will take a look

**Comment by vlasenko** [comment] 2019-08-15 17:56
@rancho90 I have tried your reproduction steps and I confirm it reproduces for me. I'm not sure why the difference in behaviour between production and development, I'm going to investigate this, hopefully tomorrow.

**Comment by vlasenko** [comment] 2019-08-16 08:26
@rancho90 I think we cannot do much here, except disabling minification for now via `--no-minify` expo option. Closing this issue, because it cannot be resolved in the kit, it should be resolved in Expo/Metro Bundler.

**Closed by vlasenko** 2019-08-16 08:26 UTC

**Comment by vlasenko** [comment] 2019-08-16 09:54
Merged #1137 into `master` and `stable` it specifies custom `minify` config for `metro` and fixes this issue.
