### ISSUE TITLE
Sign in page fails to load. Error with backend_reload

### ISSUE THREAD

**Issue by chrisbull** [sysgears/apollo-universal-starter-kit#1051] opened 2019-03-21 11:40 UTC
**Describe the bug**
Fresh install and creation build successfully, but the sign in page doesn't load and show blank page. Console says it can't resolve the dependency "backend_reload" for module "@gqlapp/core-client-react". And "backend_reload" seems to be part of SpinJS.

**To Reproduce**
1. Clean install and build
2. Click on "Sign In"
3. See blank page, and console error

**Expected behavior**
That the sign up page appears and shows correctly.

**Desktop (please complete the following information):**
 - OS: Mac Majave

**Comment by vlasenko** [comment] 2019-03-21 12:05
@chrisbull Thank you for reporting, could you attach contents of web browser javascript console and contents of terminal? I don't see this bug on Heroku, we deploy every commit from master there:
https://apollo-universal-starter-kit.herokuapp.com

**Comment by vlasenko** [comment] 2019-03-21 12:18
@chrisbull Btw, I have checked on Mac OS High Sierra, doesn't reproduce for me. Btw, did you run `yarn seed` to init sqlite3 database?

**Comment by vlasenko** [comment] 2019-03-25 07:53
@chrisbull Closing issue because of no response from topic starter

**Comment by strefethen** [comment] 2019-04-23 20:11
@vlasenko  Same problem starting a new project on OSX from scratch. 

**Describe the bug**
Following the README for getting started I'm trying to run yarn watch and getting the following error:

ERROR in /Users/strefethen/github/apollo-universal-starter-kit/node_modules/@gqlapp/core-client-react/app.tsx
Module not found: Error: Can't resolve 'backend_reload' in '/Users/strefethen/github/apollo-universal-starter-kit/node_modules/@gqlapp/core-client-react'

**To Reproduce**
Steps to reproduce the behavior:
1. git clone -b stable https://github.com/sysgears/apollo-universal-starter-kit.git
2. cd apollo-universal-starter-kit
3. yarn && yarn seed && yarn watch
4. See above error in the terminal 

**Expected behavior**
Server boots without error and the React client in the browser works as expected. With the above issue the client is essentially "dead". Clicking the buttons does nothing.

**Desktop (please complete the following information):**
 - OS: osx Mojave
 - Browser:  Brave
  - node --version - v10.15.3

**Comment by vlasenko** [comment] 2019-04-23 20:13
@strefethen Thanks for the report, I will check this first thing tomorrow morning

**Comment by vlasenko** [comment] 2019-04-23 20:16
@strefethen You can check if latest `@larix/zen` fixes this for you. You can install it by executing
`yarn add -WD @larix/zen` in the root directory of the kit

**Comment by strefethen** [comment] 2019-04-23 20:44
@vlasenko thanks for the reply. I tried installing the above package. I'm now seeing the same build error on each client. I tried:

```
yarn clean
yarn build 
```

then on yarn watch...

```
webDll-webpack error ModuleNotFoundError: Module not found: Error: Can't resolve 'jquery'
...
client-vue: zen error Error: Build error
...
mobile: zen error Error: Build error
```

**Comment by vlasenko** [comment] 2019-04-24 12:08
@chrisbull Should be fixed in `@larix/zen@0.1.10`, please upgrade and try again:
`yarn add -WD @larix/zen`
`yarn watch`

**Comment by vlasenko** [comment] 2019-04-24 12:40
Upgraded to `@larix/zen@0.1.10` in `master` and promoted `master` to `stable`

**Comment by strefethen** [comment] 2019-04-24 14:54
@vlasenko thank you.

**Closed** 2019-06-13 22:30 UTC
