### ISSUE TITLE
Graphql versions 

### ISSUE THREAD

**Issue by H1net** [sysgears/apollo-universal-starter-kit#605] opened 2018-01-09 13:40 UTC
The yarn.lock file has two graphql versions in it. The latest dependencies are causing my production build web client to fail on deployment to heroku with a console logged error regarding having two graphql versions installed.

```
Uncaught Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at r (vendor.84d87188f15089ca936a.js:51)
    at p (vendor.84d87188f15089ca936a.js:51)
    at f (vendor.84d87188f15089ca936a.js:51)
    at V (vendor.84d87188f15089ca936a.js:51)
    at W (vendor.84d87188f15089ca936a.js:51)
    at new l (vendor.84d87188f15089ca936a.js:51)
    at l (vendor.84d87188f15089ca936a.js:51)
    at Object.<anonymous> (vendor.84d87188f15089ca936a.js:51)
    at t (vendor.84d87188f15089ca936a.js:1)
    at Object.<anonymous> (index.84d87188f15089ca936a.js:1)
```

I also note that the latest graphql caused errors in some of my stubs for modules I'm working on which did not yet have Mutations/Subscriptions in the server schema.graphql. The empty stubs had to be removed to solve the problem as they caused type definition problems.

**Comment by vlasenko** [comment] 2018-01-09 13:42
@H1net Where does `yarn.lock` have two graphql versions in it?

**Comment by vlasenko** [comment] 2018-01-09 13:44
@H1net As for your second statement for the empty stubs. Yes, this is true, I have noticed this and removed empty stubs from master in the last commit:
https://github.com/sysgears/apollo-universal-starter-kit/commit/c92cfae11103645cfb7ce464b2cda31afa8d4133

**Comment by vlasenko** [comment] 2018-01-09 13:47
@H1net To have one version of GraphQL used everywhere we use `resolutions`, check here:
https://github.com/sysgears/apollo-universal-starter-kit/blob/c92cfae11103645cfb7ce464b2cda31afa8d4133/package.json#L229-L231

**Comment by H1net** [comment] 2018-01-09 13:49
Talk about lightning quick response their @vlasenko!
I assumed it was this:
```
"@types/graphql@0.10.2":
  version "0.10.2"
  resolved "https://registry.yarnpkg.com/@types/graphql/-/graphql-0.10.2.tgz#d7c79acbaa17453b6681c80c34b38fcb10c4c08c"

"@types/graphql@^0.9.0":
  version "0.9.4"
  resolved "https://registry.yarnpkg.com/@types/graphql/-/graphql-0.9.4.tgz#cdeb6bcbef9b6c584374b81aa7f48ecf3da404fa"
```

**Comment by vlasenko** [comment] 2018-01-09 14:02
@H1net `@types/graphql` is not a js code, it is rather TypeScript declarations and those are not used during runtime, they are transitive deps used by other packages that need TypeScript types during build time.

**Comment by vlasenko** [comment] 2018-01-09 14:51
Looks like the cause of this issue is described here:
https://github.com/graphql/graphql-js/issues/1182

**Comment by vlasenko** [comment] 2018-01-09 14:52
@H1net I'm going to rollback to graphql@0.11.x in the kit master for time being, until this fix will be released:
https://github.com/graphql/graphql-js/pull/1174

**Closed** 2018-01-14 18:00 UTC
